server:
    port: 8876

albedo:
    rpc:
        namespace: ${spring.application.name}
        hostUrl: localhost:8167
        zookeeper:
            connectString: localhost:2181,localhost:2182,localhost:2183







