server:
    port: 8874

albedo:
    rpc:
        namespace: ${spring.application.name}
        hostUrl: localhost:8168
        zookeeper:
            connectString: localhost:2181,localhost:2182,localhost:2183







