server:
    port: 8874
grpc:
    server:
        port: 9978
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

#server:
#    port: 0
#albedo:
#    zookeeper:
#        connectString: localhost:2181,localhost:2182,localhost:2183
#    rpc:
#        registerPath: /app/node
#        appName: hcxd-mpns-rpc-server
#        hostUrl: localhost:8181






