# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================



spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.88.247:3306/albedo-new?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: 123456
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    mvc:
#        view:
#            prefix: /WEB-INF/views/
#            suffix: .jsp
        favicon:
            enabled: false
    freemarker:
        allow-request-override: false
        cache:  false
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes:  false
        expose-session-attributes:  false
        expose-spring-macro-helpers:  true
        #prefix:
        suffix: .ftl
        template-loader-path: classpath:/WEB-INF/views/,/WEB-INF/views/ #/WEB-INF/views/
    redis :
      password : bosheng906!
      sentinel :
        nodes : 182.92.204.180:26377,182.92.204.180:26378
        master : master

server:
    port: 8070
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

albedo:
    jedisKeyPrefix: albedo-metronic
    developMode: true
    isTokenInterceptor: false
    freeURL:
    zookeeper:
        connectString: 114.55.177.236:2181,114.55.177.236:2182,114.55.177.236:2183,114.55.177.236:2184,114.55.177.236:2185
    rpc:
        registerPath: /servers/node
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 256M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: 8748a5ea8df623bc800993fbaed1090b31b049cc
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: albedoJhipster@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: albedoJhipster
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
